name : eLearning Mind - eLearning Developer Wiki
brand : eLearning Mind
description : This site is meant to be used as a resource for eLearning Mind's development team.
keyword :
url : http://elearningmind.github.io/elmdevwiki
email : developer@elearningmind.com
twitter : elearningmind
github : elearningmind
author : Jason Luna
analytics : UA-68123333-1
year : 2015
markdown : kramdown
exclude :
  - node_modules
